db:
  image: postgres
  environment:
      - POSTGRES_NAME=smarthousing
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=smarthousing

rabbitmq:
  image: tutum/rabbitmq
  environment:
    - RABBITMQ_PASS=12345
  ports:
    - "5672:5672"  # we forward this port because it's useful for debugging 
    - "15672:15672"  # here, we can access rabbitmq management plugin

# container with Django web server
web:
  restart: always
  build: .
  command: ./run_web.sh
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - rabbitmq

# container with rabbitmq worker
worker:
  build: .
  command: ./run_celery.sh
  volumes:
    - .:/code
  links:    
    - rabbitmq